let stockTienda = [
    {"id": "aaa", "nombre": "Monitor 1",   "desc": "Monitor LED 144hz", "precio": 1200, "img": "images/monitor.webp"},
    {"id": "aba", "nombre": "Monitor 2",   "desc": "Monitor LED 144hz", "precio": 1100, "img": "images/monitor.webp"},
    {"id": "aab", "nombre": "Monitor 3",   "desc": "Monitor LED 144hz", "precio": 1200, "img": "images/monitor.webp"},
    {"id": "baa", "nombre": "Monitor 4",   "desc": "Monitor LED 144hz", "precio": 1400, "img": "images/monitor.webp"},
    {"id": "bba", "nombre": "Monitor 5",   "desc": "Monitor LED 144hz", "precio": 1200, "img": "images/monitor.webp"},
    {"id": "bbb", "nombre": "Monitor 6",   "desc": "Monitor LED 144hz", "precio": 1500, "img": "images/monitor.webp"},
    {"id": "bcb", "nombre": "Teclado 1",  "desc": "Teclado Mecanico", "precio": 500, "img": "images/teclado.jpg"},
    {"id": "bbc", "nombre": "Teclado 2",  "desc": "Teclado Mecanico", "precio": 500, "img": "images/teclado.jpg"},
    {"id": "cbb", "nombre": "Teclado 3",  "desc": "Teclado Mecanico", "precio": 500, "img": "images/teclado.jpg"},
    {"id": "bcc", "nombre": "Teclado 4",  "desc": "Teclado Mecanico", "precio": 700, "img": "images/teclado.jpg"},
    {"id": "ccc", "nombre": "Teclado 5", "desc": "Teclado Mecanico", "precio": 700, "img": "images/teclado.jpg"},
    {"id": "cdc", "nombre": "Teclado 6",  "desc": "Teclado Mecanico", "precio": 700, "img": "images/teclado.jpg"},
    {"id": "ccd", "nombre": "Mouse 1",  "desc": "Mouse Inalambrico", "precio": 900, "img": "images/mouse.jpg"},
    {"id": "ddc", "nombre": "Mouse 2",  "desc": "Mouse Inalambrico", "precio": 1400, "img": "images/mouse.jpg"},
    {"id": "ddd", "nombre": "Mouse 3",  "desc": "Mouse Inalambrico", "precio": 7000, "img": "images/mouse.jpg"},
    {"id": "ded", "nombre": "Mouse 4",  "desc": "Mouse Inalambrico", "precio": 777, "img": "images/mouse.jpg"},
    {"id": "edd", "nombre": "Mouse 5",  "desc": "Mouse Inalambrico", "precio": 234, "img": "images/mouse.jpg"},
    {"id": "eed", "nombre": "Mouse 6",  "desc": "Mouse Inalambrico", "precio": 155600, "img": "images/mouse.jpg"},
    {"id": "eee", "nombre": "Sonido 1",  "desc": "Los mejores Auriculares del mercado", "precio": 1600, "img": "images/sonido.jpg"},
    {"id": "efe", "nombre": "Sonido 2",  "desc": "Los mejores Auriculares del mercado", "precio": 3200, "img": "images/sonido.jpg"},
    {"id": "fee", "nombre": "Sonido 3",  "desc": "Los mejores Auriculares del mercado", "precio": 2300, "img": "images/sonido.jpg"},
    {"id": "fff", "nombre": "Sonido 4",  "desc": "Los mejores Auriculares del mercado", "precio": 5600, "img": "images/sonido.jpg"},
    {"id": "fgf", "nombre": "Sonido 5",  "desc": "Los mejores Auriculares del mercado", "precio": 1700, "img": "images/sonido.jpg"},
    {"id": "gff", "nombre": "Sonido 6",  "desc": "Los mejores Auriculares del mercado", "precio": 800, "img": "images/sonido.jpg"}
]